CEXT-3337: Added sync events button to eventing config
AdobeDocs/commerce-extensibility pull request #235
Opened 2024-07-09 19:10 UTC by ryanjcohen

## Purpose of this pull request

This pull request (PR) adds information about the synchronize events button added to the eventing configuration section of the Commerce admin.

## Affected pages

- https://developer.adobe.com/commerce/extensibility/events/configure-commerce/

## Links to Magento Open Source code

- ...

2024-07-09 20:05 UTC, keharper requested changes

2024-07-09 20:05 UTC, keharper commented on src/pages/events/configure-commerce.md
> +Each `Event Provider` can link to multiple event subscriptions (`Event Metadata`). The event's subscriptions will be automatically linked to your `Event Provider` whenever you subscribe with the `eve
Mention the new button in the "Create event metadata in Adobe I/O" section of the `commands.md` file.

Also, remove the capitalization and special highlighting of event provider in the heading and paragraphs before and after this paragraph (lines 41, 43, and 47).

2024-07-09 20:17 UTC, ryanjcohen commented on src/pages/events/configure-commerce.md
> +Each `Event Provider` can link to multiple event subscriptions (`Event Metadata`). The event's subscriptions will be automatically linked to your `Event Provider` whenever you subscribe with the `eve
I've added mention of the button to that section of `commands.md` file

2024-07-10 14:16 UTC, keharper approved these changes

2024-07-10 14:21 UTC, merged