Add registration commands
AdobeDocs/commerce-extensibility pull request #41
Opened 2022-09-13 13:27 UTC by keharper

## Purpose of this pull request

This pull request adds documentation for the `bin/magento events:registration` command and adds new arguments to `events:create-events-provider`.

## Affected pages

-  ...

## Links to related PRs or Jira tickets

-  ...

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My changes follow the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.

2022-09-13 15:36 UTC, jhadobe requested changes

2022-09-13 15:36 UTC, jhadobe commented on src/pages/events/configure-commerce.md
> +1. Register your instance with to Adobe Identity Management Services by running the following command:
```suggestion
1. Register your instance with Adobe Identity Management Services by running the following command:
```

2022-09-13 15:36 UTC, jhadobe commented on src/pages/events/configure-commerce.md
> +1. On your local environment, run the following command to enable the new modules:
```suggestion
1. In your local environment, run the following command to enable the new modules:
```
"On" is probably fine, just sounds weird to me.

2022-09-14 13:26 UTC, oshmyheliuk commented on src/pages/events/commands.md
> +*  `event_name` identifies the event to subscribe. For example: `catalog_product_save_after`.
After the latest changes, we still can subscribe to any observer events. But can't subscribe to the plugin events as the Plugin class wasn't generated for it, we can only subscribe (enable) plugin events that were in config.php but were disabled.
Maybe we should add this as some kind of notice

2022-09-14 19:26 UTC, jhadobe approved these changes

2022-09-14 21:07 UTC, oshmyheliuk approved these changes

2022-09-15 01:52 UTC, merged