Update Cloud configuration procedure
AdobeDocs/commerce-extensibility pull request #51
Opened 2022-09-26 19:33 UTC by keharper

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

-  ...

## Links to related PRs or Jira tickets

-  ...

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My changes follow the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.

2022-09-26 20:13 UTC, jhadobe requested changes

2022-09-26 20:13 UTC, jhadobe commented on src/pages/events/configure-commerce.md
> +1. Set the URL in the **Endpoint** field to either `https://commerce-eventing-stage.adobe.io` for Stage environments or `https://commerce-eventing-stage.adobe.io` for Production environments.
```suggestion
1. Set the URL in the **Endpoint** field to either `https://commerce-eventing-stage.adobe.io` for Stage environments or `https://commerce-eventing.adobe.io` for Production environments.
```

Guessing the second link should be the same minus `-stage`.

2022-09-26 20:13 UTC, jhadobe commented on src/pages/events/configure-commerce.md
> +   * Update the `repositories` section so that it matches the following:
My linting rules for [the API-Mesh-Gateway](https://github.com/AdobeDocs/graphql-mesh-gateway) ask for 2 spaces after unordered list markers. However, I'm not sure if this is an important distinction.

2022-09-26 20:25 UTC, jhadobe commented on src/pages/events/configure-commerce.md
> +   * Update the `repositories` section so that it matches the following:
it looks like i have a `.json` file with linting rules in that repo, which has the following: `  "MD030": { "ol_single": 1, "ol_multi": 1, "ul_single": 2, "ul_multi": 2 },`. the `extensibility` repo uses a different linting configuration using aliases and doesn't refer to the `list-marker-space` alias. let me know if i should update the `API Mesh Gateway` repo to this format.

2022-09-26 20:50 UTC, jhadobe approved these changes

2022-09-27 18:48 UTC, keharper commented
I received approval in Slack:


Oleksandr Shmyheliuk
  [3:30 PM] Changes related to the Cloud configuration looks good for me.

2022-09-27 18:48 UTC, merged